//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.Web.Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/Event/AVJobBrief")]
        public string RPT_PATH_AVJ_REQ {
            get {
                return ((string)(this["RPT_PATH_AVJ_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/IT/ItRequest")]
        public string RPT_PATH_IT_REQ {
            get {
                return ((string)(this["RPT_PATH_IT_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/HR/MedicalCheckedRequestor")]
        public string RPT_PATH_MT_REQ {
            get {
                return ((string)(this["RPT_PATH_MT_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/Finance/BusinessCaseJustificationForm")]
        public string RPT_PATH_BCJ_REQ {
            get {
                return ((string)(this["RPT_PATH_BCJ_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/HR/EmployeeRequisition")]
        public string RPT_PATH_ERF_REQ {
            get {
                return ((string)(this["RPT_PATH_ERF_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/Reservation/FnFBookingRequest")]
        public string RPT_PATH_RSVNFF_REQ {
            get {
                return ((string)(this["RPT_PATH_RSVNFF_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/Reservation/CRoomRequest")]
        public string RPT_PATH_RSVNCR_REQ {
            get {
                return ((string)(this["RPT_PATH_RSVNCR_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/Event/ProjectBrief")]
        public string RPT_PATH_PBF_REQ {
            get {
                return ((string)(this["RPT_PATH_PBF_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/Maintenance/Maintenance Work Order")]
        public string RPT_PATH_MWO_REQ {
            get {
                return ((string)(this["RPT_PATH_MWO_REQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/K2Report/HR/AuthorisationToTravel")]
        public string RPT_PATH_ATT_REQ {
            get {
                return ((string)(this["RPT_PATH_ATT_REQ"]));
            }
        }
    }
}
